language: php

sudo: false

services:
  - mysql

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0

cache:
  directories:
    - $HOME/.composer/cache/files
env:
  - SYMFONY_VERSION="3.3.*" DB=mysql

before-install:
  - composer self-update

before_script:
  - composer install
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - ./vendor/bin/phpunit

notifications:
  email:
    - ps.augereau@gmail.com

