app:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods: [get,post]


security_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
    methods: [get,post]

logout:
    path: /logout

security_login_check:
    path:     /login
    defaults: { _controller: AppBundle:Security:loginCheck }
    methods: [get]

admin_import:
  resource: "@AppBundle/Resources/config/routing/admin.yml"
  prefix: /admin
