# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: [ROLE_ADMIN]}
        - { path: ^/API/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/API, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:  [ROLE_EDITOR, ROLE_NATURALIST, ROLE_OBSERVER ]
        ROLE_NATURALIST: [ROLE_NATURALIST,ROLE_OBSERVER]
        ROLE_OBSERVER: [ROLE_OBSERVER]

    providers:
        user_provider:
            entity: { class: AppBundle:User, property: email }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        login:
                pattern:  ^/API/login
                stateless: true
                anonymous: true
                form_login:
                    check_path:               /API/login_check
                    success_handler:          lexik_jwt_authentication.handler.authentication_success
                    failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                    require_previous_session: false
                    #username_parameter: email


        api:
            pattern:   ^/API
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            pattern: ^/
            anonymous: true
            provider: user_provider
            guard:
                authenticators:
                    - form_authenticator
            logout:
                path: /logout
                target: /

            remember_me:
                secret: '%secret%'

            oauth:
                resource_owners:
                    google:             "/login/check-google"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: app.oauth
