# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    twig.extension.text:
            class: Twig_Extensions_Extension_Text
            tags:
                - { name: twig.extension }
    form_authenticator:
        class: AppBundle\Security\FormAuthenticator
        arguments: ['@router', '@form.factory', '@security.user_password_encoder.generic']
    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
    app.admin:
        class: AppBundle\Service\AdminService
        public: true
        arguments: []

    app.gps:
        class: AppBundle\Service\GPSService
        public: true
        arguments: []

    app.notification:
        class: AppBundle\Service\NotificationService
        public: true
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]

    app.user:
        class: AppBundle\Service\UserService
        public: true
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", '%list_limit%', "@app.news", "@security.password_encoder", "@app.mailer"]

    app.post:
        class: AppBundle\Service\PostService
        public: true
        arguments: ["@doctrine.orm.entity_manager",'%posts_directory%', '%list_limit%']

    app.obs:
        class: AppBundle\Service\ObservationService
        public: true
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]

    app.cmt:
        class: AppBundle\Service\CommentService
        public: true
        arguments: ["@doctrine.orm.entity_manager", '%list_limit%']

    app.news:
        class: AppBundle\Service\NewsletterService
        public: true
        arguments: ["@doctrine.orm.entity_manager", "@translator"]

    app.geoloc:
        class: AppBundle\Service\GeolocService
        public: true
        arguments: ["@doctrine.orm.entity_manager", "@app.gps"]

    app.jwt:
        class: AppBundle\Service\JwtService
        public: true
        arguments: ["@security.token_storage", "@lexik_jwt_authentication.jwt_manager"]

    app.mailer:
        class: AppBundle\Mailer\Mailer
        arguments: ["@mailer", "@templating", "@translator", "%mailer_from%", "%mailer_to%", "%mailer_name%"]

    app.oauth:
        class: AppBundle\Provider\OAuthUserProvider
        public: true
        arguments: ["@doctrine",'AppBundle:User', {facebook: facebook_id, google: google_id}, "@app.user" ]


    AppBundle\EventListener\UserListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    AppBundle\EventListener\PostListener:
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }

    AppBundle\EventListener\NotificationListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    AppBundle\EventListener\CommentListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }

