admin_user_import:
    resource: "admin/user.yml"
    prefix: /user

admin_post_import:
    resource: "admin/post.yml"
    prefix: /post

admin_homepage:
    path:     /
    defaults: { _controller: AppBundle:Admin\Default:index }
    methods: [get]
