
admin_post_new:
    path:     /new
    defaults: { _controller: AppBundle:Admin\Post:new }
    methods:  [GET, POST]

admin_post_edit:
    path:     /{id}/edit
    defaults: { _controller: AppBundle:Admin\Post:edit }
    methods:  [GET, POST]

admin_post_show:
    path:     /{id}/show
    defaults: { _controller: AppBundle:Admin\Post:show }
    methods:  [GET]

admin_post_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBundle:Admin\Post:delete }
    methods:  DELETE

admin_post_index:
    path:     /{page}/{status}
    defaults: { _controller: AppBundle:Admin\Post:index, page: 1, status: 1 }
    methods:  [GET, POST]
