admin_user_search:
    path:     /search
    defaults: { _controller: AppBundle:Admin\User:search }
    methods:  POST

admin_user_search_clear:
    path:     /clearsearch
    defaults: { _controller: AppBundle:Admin\User:index, page: 1, role: 'ROLE_OBSERVER' }
    methods:  [GET, POST ]


admin_user_edit:
    path:     /{id}/edit
    defaults: { _controller: AppBundle:Admin\User:edit }
    methods:  [GET, POST,DELETE]

admin_user_update:
    path:     /{id}/update
    defaults: { _controller: AppBundle:Admin\User:update }
    methods:  [GET, POST,DELETE]

admin_user_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBundle:Admin\User:delete }
    methods:  DELETE

admin_user_index:
    path:     /{page}/{role}
    defaults: { _controller: AppBundle:Admin\User:index, page: 1, role: 'ROLE_OBSERVER' }
    methods:  [GET, POST]


